[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gantry"
authors = [{name = "Richard Rzeszutek"}]
readme = "README.md"
version = "0.2.0"
description = "Manager Dockerized services on single-host deployments."
requires-python = "~=3.10"
dependencies = [
    "click ~= 8.1",
    "jinja2 ~= 3.1",
    "jsonschema ~= 4.4",
    "ruamel.yaml ~= 0.17"
]

[project.optional-dependencies]
dev = [
    "flake8",
    "mypy",
    "pytest",
    "types-jsonschema"
]

[project.scripts]
gantry = "gantry.cli:main"
