#!/bin/bash
#
# Run one of the samples in the '/samples' folder.  The folder must contain a
# '_build.sh' file that will be sourced by this script.
set -e

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <sample-name>"
    exit 1
fi

if [[ ! -d samples/$1 ]]; then
    echo "No sample named '$1'."
    exit 1
fi

mkdir -p build
export SAMPLE_FOLDER=samples/$1
export OUTPUT_FOLDER=build/$1.docker

if [[ ! -f $SAMPLE_FOLDER/_build.sh ]]; then
    echo "Sample is missing its _build.sh file."
    exit 1
fi

source $SAMPLE_FOLDER/_build.sh
