#!/bin/bash
set -e

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <sample-name>"
    exit 1
fi

if [[ ! -d samples/$1 ]]; then
    echo "No sample named '$1'."
    exit 1
fi

mkdir -p build
export SAMPLE_FOLDER=samples/$1
export OUTPUT_FOLDER=build/$1.docker

if [[ ! -f $SAMPLE_FOLDER/_build.sh ]]; then
    echo "Sample is missing its _build.sh file."
    exit 1
fi

source $SAMPLE_FOLDER/_build.sh
