entryPoints:
  standard:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https
          permanent: true

  secure:
    address: ":443"

api:
  dashboard: true

pilot:
  dashboard: false

providers:
  docker:
    watch: true
    network: "{{ service.network }}"
    exposedByDefault: false
