name: Build a new release.

on:
  pull_request:
    types:
      - opened
      - synchronize

  release:
    types:
      - published

jobs:
  build-dist:
    name: Build gantry release.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run 'flit build' to generate source distribution and Python wheel.
        run: |
          conda env create
          conda run -n gantry --live-stream pip install --upgrade pip setuptools
          conda run -n gantry --live-stream flit build

      - name: Upload build artifacts.
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist
          if-no-files-found: error

  generate-schemas:
    name: Generate JSON schema package.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Export the JSON schemas from gantry.
        run: |
          conda env create
          conda run -n gantry --live-stream pip install --upgrade pip setuptools
          conda run -n gantry --live-stream flit install
          conda run -n gantry --live-stream gantry schemas export

      - name: Create schemas archive.
        run: tar -czvf schemas.tar.gz schemas

      - name: Upload build artifacts.
        uses: actions/upload-artifact@v3
        with:
          name: schemas
          path: schemas.tar.gz
          if-no-files-found: error

  update-release:
    name: Attach artifacts to release.
    runs-on: ubuntu-latest
    needs:
      - build-dist
      - generate-schemas
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts.
        uses: actions/download-artifacts@v3

      - name: Display contents.
        run: ls -R
