name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup conda environment and install gantry.
        run: |
          conda env create
          conda activate gantry
          flit install

      - name: Run flake8.
        run: flake8 src
