name: Run Tests

on: [pull_request]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          checksum: "909278eb197c5ed0e9b5f16317d1255270d1f9ea4196e7179ce934d48c4c2545"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Sync dependencies
        run: uv sync --only-dev

      - name: Run black
        run: uv run black --check src/ test/

      - name: Run flake8
        run: uv run flake8 src/

      - name: Display formatting errors.
        run: |
          out=$(uv run black --check src/ test/)

          echo "${out}"
          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
          echo "${out}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        if: ${{ failure() }}

  test:
    runs-on: ubuntu-latest
    needs: format-code
    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          checksum: "909278eb197c5ed0e9b5f16317d1255270d1f9ea4196e7179ce934d48c4c2545"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Sync dependencies
        run: uv sync --extra dev

      - name: Run mypy
        run: uv run ./scripts/run-mypy

      - name: Run tests
        run: uv run pytest -p no:legacypath

  build-samples:
    runs-on: ubuntu-latest
    needs: format-code
    strategy:
      fail-fast: false
      matrix:
        sample:
          - build-image
          - simple-tls

    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          checksum: "909278eb197c5ed0e9b5f16317d1255270d1f9ea4196e7179ce934d48c4c2545"
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Build '${{ matrix.sample }}'' sample.
        run: |
          uv sync
          uv run ./scripts/build-sample ${{ matrix.sample }}
