name: Run Tests

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup conda environment and install gantry.
        run: |
          conda env create
          conda run -n gantry --live-stream pip install --upgrade pip setuptools
          conda run -n gantry --live-stream flit install

      - name: Run flake8.
        run: conda run -n gantry --live-stream flake8 src

      - name: Run mypy.
        run: conda run -n gantry --live-stream python ./scripts/run-mypy

      - name: Run tests.
        run: conda run -n gantry --live-stream pytest -p no:legacypath

  build-samples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sample:
          - build-image
          - simple-tls

    steps:
      - uses: actions/checkout@v3

      - name: Build and install gantry.
        run: |
          conda env create
          conda run -n gantry --live-stream pip install --upgrade pip setuptools
          conda run -n gantry --live-stream flit install

      - name: Build '${{ matrix.sample }}'' sample.
        run: |
          conda run -n gantry --live-stream ./scripts/build-sample ${{ matrix.sample }}
